/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Goal = IDL.Record({
  'id' : IDL.Int,
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'targetDate' : Time,
  'milestones' : IDL.Vec(IDL.Text),
});
export const Habit = IDL.Record({
  'id' : IDL.Int,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'frequencyTarget' : IDL.Nat,
  'trackingHistory' : IDL.Vec(IDL.Bool),
});
export const Study = IDL.Record({
  'id' : IDL.Int,
  'subjectName' : IDL.Text,
  'description' : IDL.Text,
  'studySchedule' : IDL.Text,
  'progress' : IDL.Nat,
});
export const WorkItem = IDL.Record({
  'id' : IDL.Int,
  'projectName' : IDL.Text,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'deadline' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGoal' : IDL.Func([Goal], [], []),
  'addHabit' : IDL.Func([Habit], [], []),
  'addStudy' : IDL.Func([Study], [], []),
  'addWorkItem' : IDL.Func([WorkItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getStudies' : IDL.Func([], [IDL.Vec(Study)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkItems' : IDL.Func([], [IDL.Vec(WorkItem)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Goal = IDL.Record({
    'id' : IDL.Int,
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'targetDate' : Time,
    'milestones' : IDL.Vec(IDL.Text),
  });
  const Habit = IDL.Record({
    'id' : IDL.Int,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'frequencyTarget' : IDL.Nat,
    'trackingHistory' : IDL.Vec(IDL.Bool),
  });
  const Study = IDL.Record({
    'id' : IDL.Int,
    'subjectName' : IDL.Text,
    'description' : IDL.Text,
    'studySchedule' : IDL.Text,
    'progress' : IDL.Nat,
  });
  const WorkItem = IDL.Record({
    'id' : IDL.Int,
    'projectName' : IDL.Text,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'deadline' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGoal' : IDL.Func([Goal], [], []),
    'addHabit' : IDL.Func([Habit], [], []),
    'addStudy' : IDL.Func([Study], [], []),
    'addWorkItem' : IDL.Func([WorkItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getStudies' : IDL.Func([], [IDL.Vec(Study)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkItems' : IDL.Func([], [IDL.Vec(WorkItem)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };